version: '3'

services:
  slim:
      build: .
      working_dir: /var/www
      command: php -S 0.0.0.0:8080 -t public
      environment:
          docker: "true"
          XDEBUG_MODE: debug
          XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
      ports:
          - "8080:8080"
      volumes:
          - .:/var/www
          - logs:/var/www/logs
      depends_on:
          - mysqldb
      extra_hosts:
          host.docker.internal: host-gateway
  mysqldb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'easyLearning'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql:/var/lib/mysql
      - ./sql/easylearning (3).sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
    logs:
        driver: local
    mysql: